### ISSUE TITLE
*args with following specified kwargs does not work.

### ISSUE THREAD

**Issue by johannes-graner** [Casper321/reST-docstring-checker#13]
# Summary
Variable positional arguments cannot be followed by non-`**kwargs` keyword arguments.
## Minimal failure case
Both
```python
def test_function(arg: str, *args, exact_kwarg: bool) -> None:
    """Test function to demonstrate docstring checker failure.

    :param arg: An argument.
    :param *args: Positional arguments.
    :param exact_kwarg: Specified keyword argument.
    """
    ...
```
and
```python
def test_function(arg: str, *args, exact_kwarg: bool) -> None:
    """Test function to demonstrate docstring checker failure.

    :param arg: An argument.
    :param exact_kwarg: Specified keyword argument.
    """
    ...
```

result in a failure with message `Docstring params do not match function params in function test_function`.

## Expected behavior
At least one of the above should succeed. If the positional arguments are specified as `*`, they should not need to be included in the docstring.

## Additional context
Ruff's [FBT001](https://docs.astral.sh/ruff/rules/boolean-type-hint-positional-argument/) does not allow positional boolean arguments, so specifying something like
```python
def test_function(arg: str, *, bool_arg: bool) -> None:
    ...
```
is required. This is currently incompatible with the docstring checker.

**Comment by Casper321** [comment]
Thank you for finding this issue!
It's fixed here:
https://github.com/Casper321/reST-docstring-checker/pull/14
